# Basic
title: firestealers
subtitle: 交流技术，分享乐趣
welcome_message: A place for all hardworking scholars share excitement and enjoyment.
description: 欢迎来到道火技术乐园
creator: <a href="">jesse</a>

url: firestealers.github.io
host:
port: 8081

# comment
comment:
    disqus: daohuo # short name
    disqus_url: "https://firestealers.github.io" # site.comment.disqus_url

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 查看博客

# The home page button should not be removed.
home_page_button:
    title: 主页
    description: 返回主页

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: 主页, description: , url: '/'}

# Pagination, use a a special gem named jekyll-paginate
gems: [jekyll-paginate]
paginate: 6
paginate_path: "page/:num/"

# Social
social:
    # weibo:
    github: firestealers
    twitter: s3crety
    # gplus: 
    mail: github@daohuo.com

# no need for now
# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host
